### ISSUE TITLE
Alternative Sega CD Bios is not used after reboot

### ISSUE THREAD

**Issue by oneoogeoo** [SmokeMonsterPacks/Mega-Sg-Jailbreak#12]
After powering off and on the selected alternative Sega CD Bios is still checked in the options, But the Sega CD 2 (european PAL version) starts with its own Bios version.

The only way to use an alternative bios (after powering off and on) again ist to switch to another alternative bios.

**Comment by TheRealFlamepanther** [comment]
Same for me on US SCD 2, version 2.00

**Comment by SmokeMonsterPacks** [comment]
This should be fixed in v7.4

**Comment by frederic-mahe** [comment]
same issue with JB 7.4 (see issue #34).

**Comment by TheRealFlamepanther** [comment]
The behavior for me in 7.4 is different. If I have the system set to load carts on start up, I still get the stock (hardware) BIOS when I power on. But if I then go to "Run Cartridge" from the menu, I get the custom BIOS.
