### ISSUE TITLE
CJ Elephant Fugitive (Game Gear) not working at all. 

### ISSUE THREAD

**Issue by DrBallistyx** [SmokeMonsterPacks/Mega-Sg-Jailbreak#61]
**Describe the bug**
Upon loading, the game will either display a black screen and/or garbled graphics.

**To Reproduce**
Simply load the ROM

**Firmware version**
Firmware v7.6

**ROM name and hash values**
CJ Elephant Fugitive (USA, Europe).gg  
MD5: 30D140CBA0604578382CFF96ACA09F78

**Comment by Brianvgplayer** [comment]
Isn't that a codemasters game? Have you tried changing the extension to .gcm?

**Comment by DrBallistyx** [comment]
> Isn't that a codemasters game? Have you tried changing the extension to .gcm?

That seems to have done the trick. But now its stuck at "push start" in the main menu and no buttons on the controller work.

**Comment by BooBerry** [comment]
This should be fixed in the new jailbreak firmware released today. :)

**Comment by DrBallistyx** [comment]
I have tested it on Firmware v7.7 and can confirm it now works correctly :D

**Comment by DragonPokeBall** [comment]
> I have tested it on Firmware v7.7 and can confirm it now works correctly :D

You sure? Cause I have that current Firmware, and that game still won't work. >:P
